### ISSUE TITLE
cannot install plugin

### ISSUE THREAD

**Issue by mejrs** [Xyriella/Immersive-Ground-Markers#3]
When I install it, I get the following error:

```
2024-04-13 23:12:19 CEST [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "immersive-ground-markers" jar "N0srDIqajiE4JWi1F498YohhbrNL0LVYCY4lXnU6WA4"
2024-04-13 23:12:19 CEST [pool-3-thread-1] WARN  n.r.c.e.ExternalPluginManager - Unable to start or load external plugin "immersive-ground-markers"
java.lang.reflect.InvocationTargetException: null
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at net.runelite.client.externalplugins.ExternalPluginManager.refreshPlugins(ExternalPluginManager.java:336)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: net.runelite.client.plugins.PluginInstantiationException: java.lang.NullPointerException: Name is null
	at net.runelite.client.externalplugins.ExternalPluginManager.lambda$refreshPlugins$3(ExternalPluginManager.java:347)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: net.runelite.client.plugins.PluginInstantiationException: java.lang.NullPointerException: Name is null
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:460)
	at net.runelite.client.externalplugins.ExternalPluginManager.lambda$refreshPlugins$3(ExternalPluginManager.java:342)
	... 13 common frames omitted
Caused by: java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at com.ImmersiveGroundMarkers.ImmersiveGroundMarkersConfig$OrientationMethod.valueOf(ImmersiveGroundMarkersConfig.java:10)
	at com.ImmersiveGroundMarkers.ImmersiveGroundMarkersPlugin.startUp(ImmersiveGroundMarkersPlugin.java:293)
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:438)
	... 14 common frames omitted
2024-04-13 23:12:19 CEST [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NullPointerException: null
	at net.runelite.client.ui.ClientUI.removeNavigation(ClientUI.java:260)
	at net.runelite.client.ui.ClientToolbar.lambda$removeNavigation$1(ClientToolbar.java:52)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by Xyriella** [comment]
This should be addressed when the next update comes out as of now. Will close this issue if it is fixed for you when it releases

**Comment by mejrs** [comment]
It works now, thank you very much!
